---
# SysArmor Indexer 内部用户配置
_meta:
  type: "internalusers"
  config_version: 2

# 管理员用户
admin:
  hash: "$2a$12$VcCDgh2NDk07JGN0rjGbM.Ad41qVR/YFJcgHp0UGns5JDymv..TOG"
  reserved: true
  backend_roles:
  - "admin"
  description: "Demo admin user"

# SysArmor ETL 写入用户
sysarmor_etl:
  hash: "$2a$12$4AcgAt3nwOWGWmrMFOz/WOQhOKXfqb7dQNfLdJcHZrnw6y3RFkFHK"
  reserved: false
  backend_roles:
  - "sysarmor_writer"
  description: "SysArmor ETL service user for data ingestion"

# SysArmor 只读用户
sysarmor_reader:
  hash: "$2a$12$JJSXNfTowz7Uu5ttXfeYpeYE0arACvcwlPBStB1F.MI7f0U9Z4DGC"
  reserved: false
  backend_roles:
  - "sysarmor_reader"
  description: "SysArmor read-only user for data queries"

# Dashboards 服务用户
kibanaserver:
  hash: "$2a$12$u1ShR4l4uBS3Uv59Pa2y5.1uQuZBrPL4kqE9LXgAf3SK5.jjkdNyy"
  reserved: true
  description: "Demo kibanaserver user"

# Vector ETL 专用用户
vector_etl:
  hash: "$2a$12$n5nubfWATfQjSYHiWtUyeOxMIxFHdkAKwQkBwdBaQHsuQHSAodALa"
  reserved: false
  backend_roles:
  - "sysarmor_writer"
  description: "Vector ETL service user"

# 监控用户
sysarmor_monitor:
  hash: "$2a$12$xZOcnwYPYQ3zIadnlQIJ0eNhX1ngwMWkzrOzQNUANc8B4TxDWy7S6"
  reserved: false
  backend_roles:
  - "sysarmor_monitor"
  description: "SysArmor monitoring user"

# 备份用户
sysarmor_backup:
  hash: "$2a$12$VcCDgh2NDk07JGN0rjGbM.Ad41qVR/YFJcgHp0UGns5JDymv..TOG"
  reserved: false
  backend_roles:
  - "sysarmor_backup"
  description: "SysArmor backup user"

# 默认密码说明:
# admin: admin
# sysarmor_etl: sysarmor_etl
# sysarmor_reader: sysarmor_reader
# kibanaserver: kibanaserver
# vector_etl: vector_etl
# sysarmor_monitor: sysarmor_monitor
# sysarmor_backup: sysarmor_backup
